version: '3'
services:
  fort:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: "no"
    ports:
      - "${LOCAL_PORT}:80"
    env_file:
      - .env
    networks:
      - default
